### ISSUE TITLE
使用docker-compose配置环境失败

### ISSUE THREAD

**Issue by hnkjdaxzzq** [TremblingV5/DouTok#155]
## 使用docker-compose配置环境失败

运行这条命令`docker-compose -f ./deploy/env.yml up -d`
![image](https://github.com/user-attachments/assets/de77420b-49fb-4ba8-8f76-2f8f762e7e8d)

我的系统是wsl ubuntu 22.04
docker和docker-compose版本如下：
![image](https://github.com/user-attachments/assets/91318b40-832a-4f60-b44b-aed17bf0aa13)

**Comment by TremblingV5** [comment]
不确定是不是相应的镜像版本被更新过导致起不来，如果可以用docker logs看下更详细的log

或者使用这个：

```yaml
etcd:
    image: bitnami/etcd
    container_name: etcd
    networks:
      - total
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always
```
